# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170406_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='Description Unavailable', max_length=255),
            preserve_default=False,
        ),
    ]
